name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2


    - name: Build
      workins-directory: ${{github.workspace}}
      run: cmake -B build && cmake --build build && rm -r build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Compare ldd-repl with original ldd
      working-directory: ${{github.workspace}}
      run: cd ${{github.workspace}}/tests/ && bash get_out_and_compare.sh
      
